bayi/urls.py
from django.urls import path
from bayi import views

app_name = 'bayi'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='anasayfa'),
    path('about/', views.AboutView, name='about'),
    path('<slug>/', views.CategoriesListView.as_view(), name='category_list'),
    path('abone-ol', views.SubscriptView.as_view(), name='abone_ol'),
    path('ayrıntılar/<pk>/<slug>/<name>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('add-cart/<pk>/', views.CartItemsAddView, name='add_cart'),
    path('dashboard/<user>/', views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/sepetim/<user>/', views.ShoppingListView.as_view(), name='sepetim'),
    path('dashboard/bilgilerim/<pk>/<user>/', views.MyInformationDashBoardView, name='my_information'),
    path('siparis-özeti/<user>/<cart_number>/', views.checkout, name='checkout'),
    path('dashboard/siparişlerim/<user>/', views.OrderListView.as_view(), name='shoppinglist'),
    path('delete-cart/<cart_number>/', views.delete_cart, name='delete_cart'),
    path('remove-cart-item/<pk>/<cart_number>/', views.remove_cart_item, name='remove_cart_item'),
    path('mark_as_read/<pk>/', views.mark_as_read, name='mark_as_read'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django_ckeditor_5.views import upload_file
from bayi.models import SettingsSite

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path("ckeditor5/image_upload/", upload_file, name="ckeditor_upload_file"),
    path(r"images-handler/", include("galleryfield.urls")),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('', include('bayi.urls')),
    path('', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

try:
    site = SettingsSite.objects.latest('created')
    admin.site.site_title = site.name
    admin.site.site_header = site.name
    admin.site.index_title = site.name
    admin.site.name = site.name
except:
    pass

bayi/forms.py
from django import forms
from accounts.models import Customer
from django.contrib.auth.models import User

from bayi.models import Contact


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class CustomerForm(forms.ModelForm):
    last_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Son ödeme tarihi',
                                help_text='Şimdi ödeyecekseniz boş bırakın', required=False)

    valid = forms.BooleanField(required=True, widget=forms.CheckboxInput(attrs={'type': 'checkbox'}),
                               label='Bilgilerimin doğruluğunu kontrol ettim ve satın alma işlemini onalıyorum.')

    payment = forms.ChoiceField(
        label='Ödeme yöntemi seçiniz',
        required=True,
        choices={'': '-----', 'Nakit': 'Nakit', 'Kredi Kartı': 'Kredi Kartı', 'Borç': 'Borç'},
    )

    class Meta:
        model = Customer

        fields = ['address', 'telephone', 'payment', 'last_date', 'valid']

        widgets = {
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }

    def clean(self):
        if self.cleaned_data['payment'] == 'Borç':
            if self.cleaned_data['last_date'] is None:
                self.add_error(field='last_date', error='Borç işaretlediğiniz için son ödeme tarihini giriniz')
        return self.cleaned_data


class CustomerInformationModelForm(forms.ModelForm):
    class Meta:
        model = Customer

        fields = ['telephone', 'address', ]

        widgets = {
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('subject', 'name', 'email', 'message')
        widgets = {
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
        }

bayi/views.py
import uuid
from django.utils import timezone

from django.contrib.auth.mixins import LoginRequiredMixin
from .email import email_sender
from django.db import models
from django.shortcuts import render, redirect
from django.db.models import Q, Sum
from django.http import HttpResponseRedirect

from django.views import generic

from accounts.models import Customer, OrderModel
from .models import Product, SubscriptModel, Cart, CartItem, Contact, CaseModel, SettingsSite
from django.contrib import messages
from .forms import CustomerForm, UserForm, ContactForm, CustomerInformationModelForm
from django.core.mail import settings
from django_plotly_dash import DjangoDash
from dash import html, dcc, Output, Input, dash_table
from collections import OrderedDict
import pandas as pd
import dash_bootstrap_components as dbc


def AboutView(request):
    form = ContactForm(request.POST or None)
    try:
        site = SettingsSite.objects.latest('created')
    except SettingsSite.DoesNotExist:
        site = None
    if request.method == 'POST':
        if form.is_valid():

            form.save(commit=False)

            messages.success(request, 'Mesajınız iletilmiştir. En kısa sürede cevap vereceğiz')

            subject = "İletişim Formu"

            from_email = settings.EMAIL_HOST_USER

            obj = Contact.objects.create(
                email=form.cleaned_data['email'],
                name=form.cleaned_data['name'],
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['message'],
            )

            context = {
                'name': form.cleaned_data['name'],
                'email': form.cleaned_data['email'],
                'subject': form.cleaned_data['subject'],
                'message': form.cleaned_data['message'],
                'obj': obj,
                'site': request.META.get('HTTP_ORIGIN'),
            }

            email_sender(
                subject=subject,
                sender=from_email,
                recipients=from_email,
                template='contact',
                context=context,
            )

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        else:

            form = ContactForm()

    return render(request, 'pages/about.html', {'form': form, 'site': site})


class DashboardView(generic.ListView):
    model = Customer
    template_name = 'pages/dashboard.html'

    def get(self, request, *args, **kwargs):

        app = DjangoDash('IncomeTable', external_stylesheets=[dbc.themes.BOOTSTRAP])

        app.layout = dbc.Container(
            [
                dbc.Row(
                    [
                        dbc.Col(
                            [
                                dbc.Label('Kazanç', className='mt-3'),

                                dcc.Dropdown(
                                    options={
                                        'günlük': 'Günlük',
                                        'aylık': 'Aylık',
                                        'yıllık': 'Yıllık'
                                    },
                                    value="günlük",
                                    id="dates",
                                    clearable=False,
                                    className="dropdown mb-2",
                                ),

                                dbc.Label('Ay'),

                                dcc.Dropdown(
                                    id="months",
                                    options=[
                                        {'label': 'Ocak', 'value': 1},
                                        {'label': 'Şubat', 'value': 2},
                                        {'label': 'Mart', 'value': 3},
                                        {'label': 'Nisan', 'value': 4},
                                        {'label': 'Mayıs', 'value': 5},
                                        {'label': 'Haziran', 'value': 6},
                                    ],

                                    value=timezone.now().month,
                                    clearable=False,
                                    className="dropdown mb-2",
                                ),

                                dbc.Label('Yıl'),
                                dcc.Dropdown(
                                    id="years",
                                    options=[years.order_date.year for years in OrderModel.objects.all()],
                                    value=timezone.now().year,
                                    clearable=False,
                                    className="dropdown mb-4",
                                ),

                            ],

                        ),

                        dbc.Col(
                            [
                                html.Div(id='table-content', style={'margin-top': '3rem'}, className='mx-auto'),
                                html.Div(id='table-total'),
                            ],
                        ),
                    ]
                ),
            ],
        )

        @app.callback(
            Output('table-content', 'children'),
            Output('table-total', 'children'),
            Input('dates', 'value'),
            Input('months', 'value'),
            Input('years', 'value'),
        )
        def update_table(value, month, year):

            global obj

            if value == "günlük":
                obj = CaseModel.objects.filter(created_at__day=timezone.now().day, created_at__month=month,
                                               created_at__year=year)

            elif value == "aylık":
                obj = CaseModel.objects.filter(created_at__month=month, created_at__year=year)

            elif value == "yıllık":
                obj = CaseModel.objects.filter(created_at__year=year)

            data = OrderedDict(
                [
                    ("Ödeme Tarihi", [str(i.created_at.date()) for i in obj.all()]),
                    ("Müşteri", [str(i.order.customer.user) for i in obj.all()]),
                    ("Ürünler", [i.order.product.name for i in obj.all()]),
                    ("Birim Fiyat", [i.order.product.price for i in obj.all()]),
                    ("Adet", [str(i.order.quantity) for i in obj.all()]),
                    ("Toplam", [str(i.total) + " " + "TL" for i in obj.all()]),
                ]
            )

            total = obj.aggregate(Sum('total'))['total__sum']

            if total:
                total_income = f"{value} Toplam Kazanç: {total} TL".upper()
            else:
                total_income = f"{value} Toplam Kazanç: 0 TL".upper()

            df = pd.DataFrame(data)

            table = dash_table.DataTable(
                data=df.to_dict('records'),
                columns=[{'id': c, 'name': c} for c in df.columns],
                page_size=7,
                sort_action='native',

            )

            return table, total_income

        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=..., **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_read'] = Contact.objects.filter(is_read=False).count()
        return context


class CategoriesListView(generic.ListView):
    model = Product
    template_name = 'pages/bayi.html'

    def get_queryset(self):
        object_list = Product.objects.filter(is_stock=True, category__slug=self.kwargs['slug'])
        ara = self.request.GET.get('ara', None)
        category = str(self.kwargs['slug'].title().replace('-', ' '))
        if ara:
            object_list = object_list.filter(Q(name__icontains=ara) | Q(category__name__icontains=ara))
            messages.success(self.request,
                             f'{category} ürünlerinde {len(object_list)} ürün bulundu')
        return object_list


class ProductListView(generic.ListView):
    model = Product
    template_name = 'pages/bayi.html'

    def get_queryset(self):
        object_list = Product.objects.filter(is_stock=True)
        ara = self.request.GET.get('ara', None)
        if ara:
            object_list = object_list.filter(Q(name__icontains=ara) | Q(category__name__icontains=ara))
            messages.success(self.request, f'{len(object_list)} ürün bulundu')
        return object_list


class SubscriptView(generic.View):
    http_method_names = ['get', 'post']

    def get(self, request):
        email = request.GET.get('email', None)
        if SubscriptModel.objects.filter(email=email).exists():
            messages.info(request, "Zaten abonesiniz")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            SubscriptModel.objects.create(email=email)
            messages.success(request, "Bültenimize abone olduğunuz için teşekkür ederiz.")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'pages/detail.html'

    def get_queryset(self):
        return Product.objects.filter(is_stock=True)

    def get(self, request, *args, **kwargs):
        ara = request.GET.get('ara')
        if ara:
            return HttpResponseRedirect('/?ara={}'.format(ara))
        else:
            return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.filter(
            Q(category__slug=self.get_object().category.slug) |
            Q(category__name__icontains=self.get_object().category.name) |
            Q(price=self.get_object().price)
        )
        context['recent_list'] = products.exclude(pk=self.get_object().pk).order_by('-created')[:10]
        context['new_products'] = Product.objects.filter(is_stock=True).order_by('-created')[:10]
        return context


def CartItemsAddView(request, pk):
    product = Product.objects.get(pk=pk)

templates/pages/about.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}Hakkımızda{% endblock %}

{% block stylesheets %}<link rel="stylesheet" href="{% static 'assets/css/features.css' %}">{% endblock %}

{% block content %}

    <div class="px-4 py-5 my-5 text-center">
        <a href="/">
            <img class="d-block mx-auto mb-4 rounded" src="{% static 'assets/img/favicons/favicon.png' %}" alt=""
                 width="72" height="72">
        </a>

        <h1 class="display-5 fw-bold text-body-emphasis">Hakkımızda</h1>

        <div class="col-lg-8 mx-auto">
            <p class="lead mb-4" style="text-align: justify;">Quickly design and customize responsive mobile-first sites
                with Bootstrap, the world’s
                most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system,
                extensive prebuilt components, and powerful JavaScript plugins.</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a href="{% url 'bayi:about' %}#contact"><button type="button" class="btn btn-primary btn-lg px-4 gap-3">İletişim</button></a>
            </div>
        </div>

    </div>

    <div class="container px-4 py-5" id="featured-3">
        <h2 class="pb-2 border-bottom">İletişim</h2>
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
            <div class="feature col">
                <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#telephone"/>
                    </svg>
                </div>
                <h3 class="fs-2 text-body-emphasis">Telefon</h3>
                <p>{{ site.phone }}</p>
            </div>
            <div class="feature col">
                <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#signpost-2"/>
                    </svg>
                </div>
                <h3 class="fs-2 text-body-emphasis">Adres</h3>
                <p>{{ site.address }}.</p>
            </div>
            <div class="feature col">
                <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
                    <svg class="bi" width="1em" height="1em">
                        <use xlink:href="#envelope-at"/>
                    </svg>
                </div>
                <h3 class="fs-2 text-body-emphasis">Email</h3>
                <p>{{ site.email }}</p>
            </div>
        </div>
    </div>

    {% include 'widgets/contact.html' %}

{% endblock %}

templates/pages/dashboard.html
{% extends 'layout/base.html' %}
{% load static django_bootstrap5 plotly_dash %}

{% block title %}Dashboard{% endblock %}

{% block stylesheets %}
    <!-- Custom styles for this template -->
    <link href="{% static 'assets/css/dashboard.css' %}?{% now 'U' %}" rel="stylesheet">
{% endblock %}


{% block content %}

    {% if user.is_authenticated %}

        <div class="container-fluid">
            <div class="row">
                {% include 'includes/dashboard/sidebar.html' %}
                {% if user.is_superuser or user.is_staff %}
                    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

                        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                            <h1 class="h2">Dashboard</h1>
                        </div>

                        {% plotly_app name="IncomeTable" ratio=1 %}

                    </main>
                {% else %}
                    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                            <h1 class="h2">Dashboard</h1>
                            <div class="btn-toolbar mb-2 mb-md-0">
                                <div class="btn-group me-2">
                                    {% if cart_items %}
                                        <button type="button" class="btn btn-sm btn-outline-secondary"
                                                data-bs-toggle="modal"
                                                data-bs-target="#trashModal">
                                            <i class="bi bi-trash"></i>
                                            Sepeti Sil
                                        </button>
                                        {% include 'widgets/trashModal.html' %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        {% if 'sepetim' in request.path %}
                            <h2>Sepetim</h2>
                            <div class="table-responsive small" style="margin-bottom: 25rem;">
                                {% if cart_items %}

                                    <table class="table table-striped table-sm">
                                        <thead>
                                        <tr>
                                            <th scope="col">Ürün</th>
                                            <th scope="col">Miktar</th>
                                            <th scope="col">Birim Fiyat</th>
                                            <th scope="col">Toplam</th>
                                            <th scope="col">İşlem Tarihi</th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        {% for item in cart_items %}
                                            <tr>
                                                <td>{{ item.product }}</td>
                                                <td>{{ item.quantity }}</td>
                                                <td>{{ item.product.price }} TL</td>
                                                <td>{{ item.sub_total }} TL</td>
                                                <td>{{ cart.created }}</td>
                                                <td>
                                                    <a type="button" data-bs-toggle="modal"
                                                       data-bs-target="#editCarModal{{ item.pk }}">
                                                        <img src="{% static 'admin/img/icon-deletelink.svg' %}" alt="">
                                                    </a>
                                                </td>

                                                {% include 'widgets/editCarModal.html' %}
                                            </tr>
                                        {% endfor %}
                                        </tbody>

                                    </table>
                                    <a href="{% url 'bayi:checkout' user cart.cart_number %}">
                                        <button type="button" class="btn btn-outline-secondary float-end">Ödeme
                                            Sayfası
                                        </button>
                                    </a>

                                {% else %}
                                    <p>Sepetinizde ürün bulunamadı</p>
                                {% endif %}
                            </div>
                        {% endif %}

                        {% if 'siparişlerim' in request.path %}
                            <h2>Satın Aldıklarım</h2>
                            {% if order_list %}
                                <div class="table-responsive small" style="margin-bottom: 25rem;">

                                    <table class="table table-striped table-sm">
                                        <thead>
                                        <tr>
                                            <th scope="col">Sipariş Numarası</th>
                                            <th scope="col">Ürün</th>
                                            <th scope="col">Adet</th>
                                            <th scope="col">Brim Fiyat</th>
                                            <th scope="col">Tutar</th>
                                            <th scope="col">Borç</th>
                                            <th scope="col">Satın alma Tarihi</th>
                                            <th scope="col">Son Ödeme Tarihi</th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        {% for order in order_list %}
                                            <tr>
                                                <td>{{ order.order_number }}</td>
                                                <td>{{ order.product }}</td>
                                                <td>{{ order.quantity }}</td>
                                                <td>{{ order.product.price }} TL</td>

                                                <td>{{ order.total }} TL</td>

                                                <td>{{ order.remain }} TL</td>
                                                <td>{{ order.order_date }}</td>
                                                {% if order.last_date %}
                                                    <td>{{ order.last_date }}</td>
                                                {% else %}
                                                    <td>----</td>
                                                {% endif %}

                                            </tr>
                                        {% endfor %}

                                        <tr>
                                            <td>Toplam</td>
                                            <td></td>
                                            <td>{{ total_product }}</td>
                                            <td>{{ total }} TL</td>
                                            <td>{{ remain }} TL</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            {% else %}
                                <p>Sipariş Bulunamadı</p>
                            {% endif %}
                        {% endif %}

                        {% if 'bilgilerim' in request.path %}
                            <form action="" method="post">
                                {% csrf_token %}
                                <div class="form-group col-md-10 mx-auto">
                                    {% bootstrap_form form2 %}
                                    {% bootstrap_form form %}
                                    <button type="submit" class="btn btn-secondary float-end">Güncelle</button>
                                </div>
                            </form>
                        {% endif %}
                    </main>
                {% endif %}
            </div>
        </div>
    {% else %}
        <h2 class="text-center mt-5 mb-5"><a href="{% url 'login' %}">Giriş Yapın &raquo;</a></h2>
    {% endif %}
{% endblock %}

{% block extra_js %}
    <script src="{% static 'assets/js/dashboard.js' %}?{% now 'U' %}"></script>
{% endblock %}

templates/pages/detail.html
{% extends 'layout/base.html' %}
{% load static thumbnail %}
{% block title %}{{ object.name }}{% endblock %}

{% block stylesheets %}
    <link href="{% static 'assets/css/blog.css' %}?{% now 'U' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary" style="margin-top: 5rem;">
        <div class="col-lg-5 px-0">
            <h1 class="display-4 fst-italic">{{ object.name.title }}</h1>
            <p class="lead my-3">Kategori: {{ object.category.name.title }}</p>
            <p class="lead my-3">Fiyat: {{ object.price }} TL </p>

            <form class="card p-2 col-md-6" action="{% url 'bayi:add_cart' object.pk %}" method="get">
                <div class="input-group">
                    <input id="quantity" placeholder="Ürün Adeti" type="number" name="quantity"
                           value="{{ request.GET.quantity }}"
                           class="form-control" min="1" max="{{ object.stock }}" required>
                    <button type="submit" class="btn btn-sm btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                            <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0"/>
                        </svg>
                        Sepete Ekle
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="row g-4" style="margin-top: 2%">

        <div class="col-md-8">
            <h3 class="pb-4 mb-4 fst-italic border-bottom">
                Ürün Hakkında
            </h3>

            <article class="blog-post">
                <a href="{{ object.image.url }}">
                    {% thumbnail object.image "1920x1080" padding=True quality=100 crop="center" as im %}
                        <img src="{{ im.url }}" class="img-fluid rounded-end mb-5"
                             alt="{{ object.title }}">
                    {% endthumbnail %}
                </a>
                <div>{{ object.content|safe }}</div>
            </article>
        </div>

        <div class="col-md-4">
            <div class="position-sticky" style="top: 2rem;">
                {% if recent_list %}
                    <div>
                        <h4 class="fst-italic" style="margin-top: 4%">İlişkili ürünler</h4>
                        <ul class="list-unstyled">
                            {% for recent in recent_list %}
                                <li>
                                    <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top"
                                       href="{% url 'bayi:product_detail' recent.pk recent.category.slug recent.name|slugify %}">
                                        <div class="col-lg-8">
                                            <h6 class="mb-0">{{ recent.name.title }}</h6>
                                            <small class="text-body-secondary">{{ recent.category.name.title }}</small>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                {% endif %}
                {% if new_products %}
                    <div>
                        <h4 class="fst-italic" style="margin-top: 4%">Yeni gelen ürünler</h4>
                        <ul class="list-unstyled">
                            {% for new_product in new_products %}
                                <li>
                                    <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top"
                                       href="{% url 'bayi:product_detail' new_product.pk new_product.category.slug new_product.name|slugify %}">
                                        <div class="col-lg-8">
                                            <h6 class="mb-0">{{ new_product.name.title }}</h6>
                                            <small class="text-body-secondary">{{ new_product.category.name.title }}</small>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}