bayi/urls.py
from django.urls import path
from bayi import views

app_name = 'bayi'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='anasayfa'),
    path('about/', views.AboutView, name='about'),
    path('<slug>/', views.CategoriesListView.as_view(), name='category_list'),
    path('abone-ol', views.SubscriptView.as_view(), name='abone_ol'),
    path('ayrıntılar/<pk>/<slug>/<name>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('add-cart/<pk>/', views.CartItemsAddView, name='add_cart'),
    path('dashboard/<user>/', views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/sepetim/<user>/', views.ShoppingListView.as_view(), name='sepetim'),
    path('dashboard/bilgilerim/<pk>/<user>/', views.MyInformationDashBoardView, name='my_information'),
    path('siparis-özeti/<user>/<cart_number>/', views.checkout, name='checkout'),
    path('dashboard/siparişlerim/<user>/', views.OrderListView.as_view(), name='shoppinglist'),
    path('delete-cart/<cart_number>/', views.delete_cart, name='delete_cart'),
    path('remove-cart-item/<pk>/<cart_number>/', views.remove_cart_item, name='remove_cart_item'),
    path('mark_as_read/<pk>/', views.mark_as_read, name='mark_as_read'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django_ckeditor_5.views import upload_file
from bayi.models import SettingsSite

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path("ckeditor5/image_upload/", upload_file, name="ckeditor_upload_file"),
    path(r"images-handler/", include("galleryfield.urls")),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('', include('bayi.urls')),
    path('', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

try:
    site = SettingsSite.objects.latest('created')
    admin.site.site_title = site.name
    admin.site.site_header = site.name
    admin.site.index_title = site.name
    admin.site.name = site.name
except:
    pass

templates/widgets/contact.html
{% load django_bootstrap5 %}

<!-- İletişim -->
<form action="" method="post">
    {% csrf_token %}
    <div class="px-4 pt-5 my-5 border-bottom" id="contact">
        <h1 class="display-5 fw-bold text-body-emphasis text-center fst-italic">İletişim Formu</h1>
        <hr class="mb-5">
        <div class="col-lg-6 mx-auto">
            {% bootstrap_form form %}
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
                <button type="submit" class="w-100 btn btn-primary px-4 btn-lg">Gönder</button>
            </div>
        </div>
    </div>
</form>

templates/widgets/darkmod.html
{% include 'includes/icons.html' %}

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>

templates/widgets/editCarModal.html
<!-- Modal -->
<div class="modal fade" id="editCarModal{{ item.pk }}" tabindex="-1" aria-labelledby="editCarModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="editCarModalLabel">Ürün Silme</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{ item.product }} ürününü sepetinizden kaldırmak istiyormusunuz ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" >Kapat</button>
                <a href="{% url 'bayi:remove_cart_item' item.pk item.cart.cart_number %}">
                    <button type="button" class="btn btn-danger">Sil</button>
                </a>
            </div>
        </div>
    </div>
</div>

templates/widgets/messages.html
{% if messages %}
    {% for message in messages %}

        <div class="alert alert-{{ message.tags }} alert-dismissible shadow-soft fade show mt-1" role="alert">

            <span class="alert-inner--icon">
                {% if message.tags == 'error' %}
                    <span class="bi bi-hand-thumbs-down"></span>
                {% elif message.tags == 'success' %}
                    <span class="bi bi-hand-thumbs-up"></span>
                {% elif message.tags == 'info' %}
                    <span class="bi bi-info-circle"></span>
                {% elif message.tags == 'warning' %}
                    <span class="bi bi-info-circle"></span>
                {% endif %}
            </span>

            <span class="alert-inner--text"><strong>{{ message }}</strong></span>

            {% if object_list %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {% elif 'bilgilerim' in request.path %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {% elif 'siparis-özeti' in request.path %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {% elif 'ayrıntılar' in request.path %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {% else %}
                <a href="{% url 'bayi:anasayfa' %}">
                    <button type="button" class="btn-close"></button>
                </a>
            {% endif %}

        </div>
    {% endfor %}
{% endif %}

templates/widgets/subscript.html
<!-- Subscripts Modal -->
<div class="modal fade" id="subscripts" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Abone Ol</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            
            <form action="{% url 'bayi:abone_ol' %}" method="get">
                <div class="modal-body">
                    <p>Abone olun ve ürünlerimiz ve hizmetlerimizle ilgili en son haberleri alın!</p>
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Email Adres</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1"
                               placeholder="name@example.com" name="email" value="{{request.GET.email}}" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                    <button type="submit" class="btn btn-primary">Abone ol</button>
                </div>
            </form>

        </div>
    </div>
</div>

templates/widgets/trashModal.html
<!-- Modal -->
<div class="modal fade" id="trashModal" tabindex="-1"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Sepeti Sil</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Sepetinizdeki ürünler silinecektir ! Onaylıyormusunuz ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Kapat
                </button>
                {% if "sepetim" in request.path %}
                    <a href="{% url 'bayi:delete_cart' cart.cart_number %}">
                        <button type="button" class="btn btn-primary">Onaylıyorum</button>
                    </a>
                {% elif "siparişlerim" in request.path %}
                    <a href="{% url 'bayi:delete_cart' order_number.order_number %}">
                        <button type="button" class="btn btn-primary">Onaylıyorum</button>
                    </a>
                {% endif %}

            </div>
        </div>
    </div>
</div>