bayi/urls.py
from django.urls import path
from bayi import views

app_name = 'bayi'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='anasayfa'),
    path('about/', views.AboutView, name='about'),
    path('<slug>/', views.CategoriesListView.as_view(), name='category_list'),
    path('abone-ol', views.SubscriptView.as_view(), name='abone_ol'),
    path('ayrıntılar/<pk>/<slug>/<name>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('add-cart/<pk>/', views.CartItemsAddView, name='add_cart'),
    path('dashboard/<user>/', views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/sepetim/<user>/', views.ShoppingListView.as_view(), name='sepetim'),
    path('dashboard/bilgilerim/<pk>/<user>/', views.MyInformationDashBoardView, name='my_information'),
    path('siparis-özeti/<user>/<cart_number>/', views.checkout, name='checkout'),
    path('dashboard/siparişlerim/<user>/', views.OrderListView.as_view(), name='shoppinglist'),
    path('delete-cart/<cart_number>/', views.delete_cart, name='delete_cart'),
    path('remove-cart-item/<pk>/<cart_number>/', views.remove_cart_item, name='remove_cart_item'),
    path('mark_as_read/<pk>/', views.mark_as_read, name='mark_as_read'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django_ckeditor_5.views import upload_file
from bayi.models import SettingsSite

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path("ckeditor5/image_upload/", upload_file, name="ckeditor_upload_file"),
    path(r"images-handler/", include("galleryfield.urls")),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('', include('bayi.urls')),
    path('', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

try:
    site = SettingsSite.objects.latest('created')
    admin.site.site_title = site.name
    admin.site.site_header = site.name
    admin.site.index_title = site.name
    admin.site.name = site.name
except:
    pass

bayi/forms.py
from django import forms
from accounts.models import Customer
from django.contrib.auth.models import User

from bayi.models import Contact


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class CustomerForm(forms.ModelForm):
    last_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Son ödeme tarihi',
                                help_text='Şimdi ödeyecekseniz boş bırakın', required=False)

    valid = forms.BooleanField(required=True, widget=forms.CheckboxInput(attrs={'type': 'checkbox'}),
                               label='Bilgilerimin doğruluğunu kontrol ettim ve satın alma işlemini onalıyorum.')

    payment = forms.ChoiceField(
        label='Ödeme yöntemi seçiniz',
        required=True,
        choices={'': '-----', 'Nakit': 'Nakit', 'Kredi Kartı': 'Kredi Kartı', 'Borç': 'Borç'},
    )

    class Meta:
        model = Customer

        fields = ['address', 'telephone', 'payment', 'last_date', 'valid']

        widgets = {
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }

    def clean(self):
        if self.cleaned_data['payment'] == 'Borç':
            if self.cleaned_data['last_date'] is None:
                self.add_error(field='last_date', error='Borç işaretlediğiniz için son ödeme tarihini giriniz')
        return self.cleaned_data


class CustomerInformationModelForm(forms.ModelForm):
    class Meta:
        model = Customer

        fields = ['telephone', 'address', ]

        widgets = {
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('subject', 'name', 'email', 'message')
        widgets = {
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
        }

bayi/views.py
import uuid
from django.utils import timezone

from django.contrib.auth.mixins import LoginRequiredMixin
from .email import email_sender
from django.db import models
from django.shortcuts import render, redirect
from django.db.models import Q, Sum
from django.http import HttpResponseRedirect

from django.views import generic

from accounts.models import Customer, OrderModel
from .models import Product, SubscriptModel, Cart, CartItem, Contact, CaseModel, SettingsSite
from django.contrib import messages
from .forms import CustomerForm, UserForm, ContactForm, CustomerInformationModelForm
from django.core.mail import settings
from django_plotly_dash import DjangoDash
from dash import html, dcc, Output, Input, dash_table
from collections import OrderedDict
import pandas as pd
import dash_bootstrap_components as dbc


def AboutView(request):
    form = ContactForm(request.POST or None)
    try:
        site = SettingsSite.objects.latest('created')
    except SettingsSite.DoesNotExist:
        site = None
    if request.method == 'POST':
        if form.is_valid():

            form.save(commit=False)

            messages.success(request, 'Mesajınız iletilmiştir. En kısa sürede cevap vereceğiz')

            subject = "İletişim Formu"

            from_email = settings.EMAIL_HOST_USER

            obj = Contact.objects.create(
                email=form.cleaned_data['email'],
                name=form.cleaned_data['name'],
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['message'],
            )

            context = {
                'name': form.cleaned_data['name'],
                'email': form.cleaned_data['email'],
                'subject': form.cleaned_data['subject'],
                'message': form.cleaned_data['message'],
                'obj': obj,
                'site': request.META.get('HTTP_ORIGIN'),
            }

            email_sender(
                subject=subject,
                sender=from_email,
                recipients=from_email,
                template='contact',
                context=context,
            )

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        else:

            form = ContactForm()

    return render(request, 'pages/about.html', {'form': form, 'site': site})


class DashboardView(generic.ListView):
    model = Customer
    template_name = 'pages/dashboard.html'

    def get(self, request, *args, **kwargs):

        app = DjangoDash('IncomeTable', external_stylesheets=[dbc.themes.BOOTSTRAP])

        app.layout = dbc.Container(
            [
                dbc.Row(
                    [
                        dbc.Col(
                            [
                                dbc.Label('Kazanç', className='mt-3'),

                                dcc.Dropdown(
                                    options={
                                        'günlük': 'Günlük',
                                        'aylık': 'Aylık',
                                        'yıllık': 'Yıllık'
                                    },
                                    value="günlük",
                                    id="dates",
                                    clearable=False,
                                    className="dropdown mb-2",
                                ),

                                dbc.Label('Ay'),

                                dcc.Dropdown(
                                    id="months",
                                    options=[
                                        {'label': 'Ocak', 'value': 1},
                                        {'label': 'Şubat', 'value': 2},
                                        {'label': 'Mart', 'value': 3},
                                        {'label': 'Nisan', 'value': 4},
                                        {'label': 'Mayıs', 'value': 5},
                                        {'label': 'Haziran', 'value': 6},
                                    ],

                                    value=timezone.now().month,
                                    clearable=False,
                                    className="dropdown mb-2",
                                ),

                                dbc.Label('Yıl'),
                                dcc.Dropdown(
                                    id="years",
                                    options=[years.order_date.year for years in OrderModel.objects.all()],
                                    value=timezone.now().year,
                                    clearable=False,
                                    className="dropdown mb-4",
                                ),

                            ],

                        ),

                        dbc.Col(
                            [
                                html.Div(id='table-content', style={'margin-top': '3rem'}, className='mx-auto'),
                                html.Div(id='table-total'),
                            ],
                        ),
                    ]
                ),
            ],
        )

        @app.callback(
            Output('table-content', 'children'),
            Output('table-total', 'children'),
            Input('dates', 'value'),
            Input('months', 'value'),
            Input('years', 'value'),
        )
        def update_table(value, month, year):

            global obj

            if value == "günlük":
                obj = CaseModel.objects.filter(created_at__day=timezone.now().day, created_at__month=month,
                                               created_at__year=year)

            elif value == "aylık":
                obj = CaseModel.objects.filter(created_at__month=month, created_at__year=year)

            elif value == "yıllık":
                obj = CaseModel.objects.filter(created_at__year=year)

            data = OrderedDict(
                [
                    ("Ödeme Tarihi", [str(i.created_at.date()) for i in obj.all()]),
                    ("Müşteri", [str(i.order.customer.user) for i in obj.all()]),
                    ("Ürünler", [i.order.product.name for i in obj.all()]),
                    ("Birim Fiyat", [i.order.product.price for i in obj.all()]),
                    ("Adet", [str(i.order.quantity) for i in obj.all()]),
                    ("Toplam", [str(i.total) + " " + "TL" for i in obj.all()]),
                ]
            )

            total = obj.aggregate(Sum('total'))['total__sum']

            if total:
                total_income = f"{value} Toplam Kazanç: {total} TL".upper()
            else:
                total_income = f"{value} Toplam Kazanç: 0 TL".upper()

            df = pd.DataFrame(data)

            table = dash_table.DataTable(
                data=df.to_dict('records'),
                columns=[{'id': c, 'name': c} for c in df.columns],
                page_size=7,
                sort_action='native',

            )

            return table, total_income

        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=..., **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_read'] = Contact.objects.filter(is_read=False).count()
        return context


class CategoriesListView(generic.ListView):
    model = Product
    template_name = 'pages/bayi.html'

    def get_queryset(self):
        object_list = Product.objects.filter(is_stock=True, category__slug=self.kwargs['slug'])
        ara = self.request.GET.get('ara', None)
        category = str(self.kwargs['slug'].title().replace('-', ' '))
        if ara:
            object_list = object_list.filter(Q(name__icontains=ara) | Q(category__name__icontains=ara))
            messages.success(self.request,
                             f'{category} ürünlerinde {len(object_list)} ürün bulundu')
        return object_list


class ProductListView(generic.ListView):
    model = Product
    template_name = 'pages/bayi.html'

    def get_queryset(self):
        object_list = Product.objects.filter(is_stock=True)
        ara = self.request.GET.get('ara', None)
        if ara:
            object_list = object_list.filter(Q(name__icontains=ara) | Q(category__name__icontains=ara))
            messages.success(self.request, f'{len(object_list)} ürün bulundu')
        return object_list


class SubscriptView(generic.View):
    http_method_names = ['get', 'post']

    def get(self, request):
        email = request.GET.get('email', None)
        if SubscriptModel.objects.filter(email=email).exists():
            messages.info(request, "Zaten abonesiniz")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            SubscriptModel.objects.create(email=email)
            messages.success(request, "Bültenimize abone olduğunuz için teşekkür ederiz.")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'pages/detail.html'

    def get_queryset(self):
        return Product.objects.filter(is_stock=True)

    def get(self, request, *args, **kwargs):
        ara = request.GET.get('ara')
        if ara:
            return HttpResponseRedirect('/?ara={}'.format(ara))
        else:
            return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.filter(
            Q(category__slug=self.get_object().category.slug) |
            Q(category__name__icontains=self.get_object().category.name) |
            Q(price=self.get_object().price)
        )
        context['recent_list'] = products.exclude(pk=self.get_object().pk).order_by('-created')[:10]
        context['new_products'] = Product.objects.filter(is_stock=True).order_by('-created')[:10]
        return context


def CartItemsAddView(request, pk):
    product = Product.objects.get(pk=pk)

templates/includes/bayi/cards.html
{% load thumbnail product django_bootstrap5 %}

<!-- Bayi -->
{% if object_list %}
    <h3 class="pb-4 mb-4 fst-italic border-bottom" style="margin-top: 5rem">
        {% if request.path == '/' %}
            Tüm Ürünler
        {% else %}
            {{ request.get_full_path|breadcrumbs|title }}
        {% endif %}
    </h3>
    <!-- Ürünler -->
    <div class="row mb-2">
        {% for object in object_list %}
            <!-- {{ object.name }} -->
            <div class="col-md-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary-emphasis">{{ object.category.name.title }}</strong>
                        <h3 class="mb-0">{{ object.name }}</h3>
                        <p class="card-text mb-auto">{{ object.price }} TL</p>
                        <a href="{% url 'bayi:product_detail' object.pk object.category.slug object.name|slugify %}"
                           class="icon-link gap-1 icon-link-hover stretched-link">
                            Ayrıntılar
                            <svg class="bi">
                                <use xlink:href="#chevron-right"/>
                            </svg>
                        </a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        {% thumbnail object.image "200x250" padding=True quality=100 crop="center" as im %}
                            <img src="{{ im.url }}" class="img-fluid rounded-end"
                                 alt="{{ object.title }}">
                        {% endthumbnail %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endif %}

templates/includes/bayi/footer.html
{% load settings static %}
{% get_setting as obj %}

<!-- Footer -->
<div class="container mb-5" style="margin-top: 5rem;">
    <hr class="mb-5">
    <ul class="nav justify-content-center pb-3 mb-3">
        <li class="nav-item"><a href="/" class="nav-link px-2 text-body-secondary">Anasayfa</a></li>
        <li class="nav-item"><a href="{% url 'bayi:about' %}" class="nav-link px-2 text-body-secondary">Hakkımızda</a></li>
        <li class="nav-item"><a href="{% url 'bayi:about' %}#contact" class="nav-link px-2 text-body-secondary">İletişim</a></li>
        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link px-2 text-body-secondary">Giriş yap</a></li>
    </ul>
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                {% if obj.favicon %}
                    <img src="{{ obj.favicon.url }}" alt="" width="32" height="32" class="rounded-circle">
                {% else %}
                    <img src="{% static 'assets/img/favicons/favicon.png' %}" alt="" width="32" height="32"
                         class="rounded-circle">
                {% endif %}
            </a>
            <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 {{ obj.name.title }}, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-body-secondary"
                                href="https://api.whatsapp.com/send?text={{ request.build_absolute_uri }}">
                <svg class="bi" width="24" height="24">
                    <use xlink:href="#whatsapp"/>
                </svg>
            </a></li>
            <li class="ms-3"><a class="text-body-secondary"
                                href="https://twitter.com/intent/tweet?text={{ request.build_absolute_uri }}">
                <svg class="bi" width="24" height="24">
                    <use xlink:href="#twitter"/>
                </svg>
            </a></li>
            <li class="ms-3"><a class="text-body-secondary"
                                href="https://www.linkedin.com/cws/share/?url={{ request.build_absolute_uri }}">
                <svg class="bi" width="24" height="24">
                    <use xlink:href="#linkedin"/>
                </svg>
            </a></li>
        </ul>
    </footer>
</div>

templates/includes/bayi/header.html
{% load header %}
{% get_header as header %}

{% if header %}
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary" style="margin-top: 5rem;">
        <div class="col-lg-10 px-0">
            <h1 class="display-5 fst-italic">{{ header.title.title }}</h1>
            <p class="lead my-3">{{ header.content|safe }}</p>
        </div>
    </div>
{% else %}

{% endif %}

templates/includes/bayi/navbar.html
{% load settings static product %}
{% get_setting as obj %}
{% get_product_category as category_list %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" aria-label="Offcanvas navbar large">

    <div class="container-fluid">

        <a class="navbar-brand" href="/">{{ obj.name.title }}</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2"
                aria-controls="offcanvasNavbar2" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">

            <div class="offcanvas-header">

                {% if user.is_authenticated %}
                    <h5 class="offcanvas-title" id="offcanvasNavbar2Label">Hoşgeldiniz {{ user }}</h5>
                {% endif %}

                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close">
                </button>

            </div>

            <div class="offcanvas-body">

                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Anasayfa</a>
                    </li>


                    <li class="nav-item dropdown">

                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Kategoriler
                        </a>

                        <ul class="dropdown-menu">

                            {% for category in category_list %}
                                <li>
                                    <a class="dropdown-item"
                                       href="{% url 'bayi:category_list' category.slug %}">{{ category.name.title }}</a>
                                </li>
                            {% endfor %}

                            <li><hr class="dropdown-divider"></li>

                            <li><a class="dropdown-item" href="/">Tümü</a></li>

                        </ul>
                    </li>

                    <li class="nav-item dropdown">

                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Profil
                        </a>

                        <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
                                {% if user.is_superuser or user.is_staff %}

                                    <li>
                                        <a class="dropdown-item" href="{% url 'bayi:dashboard' user %}">
                                            <i class="bi bi-speedometer"></i> Dashboard</a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item" href="{% url 'admin:index' %}bayi/product/add/">
                                            <i class="bi bi-file-earmark-plus-fill"></i> Ürün Ekle
                                        </a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item" href="{% url 'admin:index' %}"><i
                                                class="bi bi-person-circle"></i> Admin Paneli</a>
                                    </li>

                                {% else %}

                                    <li><a class="dropdown-item" aria-current="page"
                                           href="{% url 'bayi:shoppinglist' user %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
                                            <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"/>
                                        </svg>
                                        Siparişlerim
                                    </a></li>

                                    <li>
                                        <a class="dropdown-item" aria-current="page"
                                           href="{% url 'bayi:sepetim' request.user %}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                 fill="currentColor"
                                                 class="bi bi-cart text-info" viewBox="0 0 16 16">
                                                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
                                            </svg>
                                            Sepetim
                                        </a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item" aria-current="page"
                                           href="{% url 'bayi:my_information' request.user.pk user %}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                 fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                                <path fill-rule="evenodd"
                                                      d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                                            </svg>
                                            Bilgilerim
                                        </a>
                                    </li>

                                {% endif %}

                                <li><hr class="dropdown-divider"></li>

                                <li>
                                    <form action="{% url 'logout' %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="dropdown-item ">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                 fill="currentColor" class="bi bi-box-arrow-in-right text-danger"
                                                 viewBox="0 0 16 16">
                                                <path fill-rule="evenodd"
                                                      d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z"/>
                                                <path fill-rule="evenodd"
                                                      d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                                            </svg>
                                            Çıkış
                                        </button>
                                    </form>
                                </li>

                            {% else %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'login' %}">Giriş / Üye ol</a>
                                </li>
                            {% endif %}
                        </ul>

                    </li>

                    <li class="nav-item dropdown">

                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Diğer
                        </a>

                        <ul class="dropdown-menu">

                            <li>
                                <a class="dropdown-item" href="{% url 'bayi:about' %}#contact">İletişim</a>
                            </li>

                            <li><a class="dropdown-item" href="{% url 'bayi:about' %}">Hakkımızda</a></li>

                            <li>
                                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#subscripts">Abone ol</a>
                            </li>

                        </ul>
                    </li>
                </ul>

                <form class="d-flex mt-3 mt-lg-0" role="search" method="get" action="{% url 'bayi:anasayfa' %}">
                    <input class="form-control me-2" type="search" placeholder="Kategori veya Başlık"
                           aria-label="Search" name="ara" value="{{ request.GET.ara }}">
                    <button class="btn btn-outline-success" type="submit">Ara</button>
                </form>

            </div>

        </div>

    </div>

</nav>